export class objectAssignedUser{
    constructor(){
        this.id = 0;
        this.objectAssignedWorkflowID = null;
        this.revision = null;
        this.categoryid = null;
        this.userID = null;
        this.planCompleteDate = null;
        this.actualDate = null;
        this.isOverDue = null;
        this.isComplete = null;
        this.assignedBy = null;
        this.currentWorkflowStepId = null;
        this.currentWorkflowStepName = null;
        this.workflowId = null;
        this.workflowName = null;
        this.isReject = null;
        this.canReject = null;
        this.projectId = null;
        this.projectName = null;
        this.refId = null;
        this.commentContent = null;
        this.isFinal = null;
        this.actionTypeId = null;
        this.actionTypeName = null;
        this.workingStatus = null;
        this.isReassign = null;
        this.isLeaf = null;
        this.status = null;
        this.userFullName = null;
        this.isCompleteReject = null;
        this.packageId = null;
        this.packageName = null;
        this.notChangeUser = null;
        this.isSendOverDue = null;
        this.completedByID = null;
        this.completedByFullName = null;
        this.userNextSteps = [];
    }
}